### ISSUE TITLE
Erlang/OTP 23 support

### ISSUE THREAD

**Issue by debalance** [processone/epam#9]
Please see https://bugs.debian.org/961652

**Comment by debalance** [comment]
There's a proposed patch in the Debian bugreport now.

**Comment by prefiks** [comment]
Hello,
I commited dc6e01da958b8dd21bb6e261aa185066e427e6f2 that should fix this.

This uses a bit different approach than patch from debian bug, instead of using ei library, it uses custom serialization to binary, mostly to make it work with older versions of erlang, i think that patch do require R22.

**Comment by badlop** [comment]
> i think that patch do require R22.

I've applied Sergei Golovan's patch in the **otp23** experimental branch and compiles correctly from 19.3 to 23.
https://travis-ci.org/github/processone/ejabberd/builds/692260689

And your patch works too from 19.3 to 23, I've just checked in branch **otp23b**
https://travis-ci.org/github/processone/ejabberd/builds/692291346
